version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"  # Zookeeper portini ochish

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Kafka Zookeeper'ga ulanadi
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.136.128:9092  # Tashqi ulanish uchun broker adresi (vm manzili)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Kafka barcha interfeyslarni tinglaydi
      KAFKA_BROKER_ID: 1  # Broker ID (klasterda noyob bo'lishi kerak)
    ports:
      - "9092:9092"  # Kafka portini ochish
    depends_on:
      - zookeeper  # Kafka konteyneri Zookeeper konteyneriga tayanadi
